Car Price prediction/Controllers/adminController.cs
using Car_Price_prediction.view_model;
using Car_Price_prediction.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace Car_Price_prediction.Controllers
{
    [Authorize(Roles = "Admin")]
    public class adminController : Controller
    {
        // GET: admin
        ApplicationDbcontext _Context = new ApplicationDbcontext();
        public ActionResult USER_Accounts()
        {
            // map  Vm to identity user 
            var Users = _Context.Users.Select(x => new Registration_Vm
            {

                Name = x.Name,
                User_Name = x.UserName,
                Email = x.Email,
                phone_num = x.PhoneNumber,
                Age = x.age,
                ID = x.Id,
                Password = x.PasswordHash

            }).ToList();

            return View(Users);
        }
        public ActionResult User_massage()
        {
            var messages = _Context.CustomerMessages.ToList();
            return View(messages);
        }
        public ActionResult SellsCar()
        {
            var sells = _Context.Cars.Select(x => new SellsVM
            {
                ID = x.ID,
                UserID = x.UserID,
                Brand = x.Brand,
                Body = x.Body,
                Fuel = x.Fuel,
                Engine_CC = x.Engine_CC,
                Color = x.Color,
                City = x.City,
                Transmission = x.Transmission,
                Kilometers_Driven = x.Kilometers_Driven,
                Fabrica = x.Fabrica,
                Discription = x.Discription,
                Frontimage = _Context.carImages.FirstOrDefault(c =>c.CarID ==x.ID).Frontimage,
                Backimage = _Context.carImages.FirstOrDefault(c => c.CarID == x.ID).Backimage,
                RightSideimage = _Context.carImages.FirstOrDefault(c => c.CarID == x.ID).RightSideimage,
                Year = x.Year,
                Model = x.Model,
                Price = x.Price,
                Email = x.User.Email,
                PhoneNumber = x.User.PhoneNumber,
                UserName = _Context.Users.FirstOrDefault(a=>a.Id == x.UserID).Name
            }).Where(c => c.UserID != null)
            .ToList();
            return View(sells);
        }

        public ActionResult BussnesAccount()
        {


            var rols = _Context.Roles.Select(x => x.Name).ToList();
            ViewBag.Roles = new MultiSelectList(rols);

            return View();
        }

        [HttpPost]
        public ActionResult BussnesAccount(Registration_Vm Reg, String RoleName, HttpPostedFileBase image)
        {
            var rols = _Context.Roles.Select(x => x.Name).ToList();
            ViewBag.Roles = new MultiSelectList(rols);
            if (ModelState.IsValid)
            {
                ApplicationDbcontext _Context = new ApplicationDbcontext();
                UserStore<ApplicationUser> store = new UserStore<ApplicationUser>(_Context);
                UserManager<ApplicationUser> manager = new UserManager<ApplicationUser>(store);
                // map  Vm to identity user 
                ApplicationUser identityUser = new ApplicationUser();
                identityUser.UserName = Reg.User_Name;
                identityUser.Name = Reg.Name;
                identityUser.Email = Reg.Email;
                identityUser.PhoneNumber = Reg.phone_num;
                identityUser.Buss_img = Path.GetFileName(image.FileName);
                ViewBag.img = identityUser.Buss_img.Where(c => c.Equals(User.Identity.Name == identityUser.Name)).ToList();

                IdentityResult result = manager.Create(identityUser, Reg.Password);
                if (result.Succeeded && image.ContentLength > 0)
                {
                    manager.AddToRole(identityUser.Id, RoleName);

                    string ImageFileName = Path.GetFileName(image.FileName);

                    string FolderPath = Path.Combine(Server.MapPath("~/img/User_img/") + ImageFileName);
                    image.SaveAs(FolderPath);
                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item);
                    }

                }
            }
            return View(Reg);
        }
    
    
       [HttpPost]
        public ActionResult Delete(string UserId)
        {
            var foundID = _Context.Users.Find(UserId);
            if (foundID == null)
            {

                return RedirectToAction("notFound", "home");
            }
            try
            {
                var user = _Context.Users.Find(UserId);
                _Context.Users.Remove(user);
                _Context.SaveChanges();
                return RedirectToAction("USER_Accounts");
            }
            catch (Exception)
            {
                return RedirectToAction("error");
                throw;
            }
        }


        public ActionResult Deletecar(int Id)
        {
            var foundID = _Context.Cars.Find(Id);
            if (foundID == null)
            {

                return RedirectToAction("notFound", "home");
            }
            try
            {
                var car = _Context.Cars.Find(Id);
                _Context.Cars.Remove(car);
                _Context.SaveChanges();
                return RedirectToAction("SellsCar");
            }
            catch (Exception)
            {
                return RedirectToAction("error");
                throw;
            }

        }
    }

}

Car Price prediction/Views/admin/BussnesAccount.cshtml
@model Car_Price_prediction.view_model.Registration_Vm


@{
    ViewBag.Title = "BussnesAccount";
    ViewBag.icon = "BussnesAccount.png";
}

<head>
    <link href="~/Content/log_reg.css" rel="stylesheet" />
</head>

@using (Html.BeginForm("BussnesAccount", "admin",FormMethod.Post, new { enctype = "multipart/form-data", @class = "form", id = "Filterform" }))
{

    @Html.AntiForgeryToken()

    <section class="form-02-main">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="_lk_de">

                        <div style="text-align:center">
                            <h2>ADD Account to Business Role </h2>
                        </div>
                        <div class="form-03-main">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group p-0 wow bounceInLeft " data-wow-delay="0.1s">
                                @Html.EditorFor(model => model.User_Name, new { htmlAttributes = new { @placeholder = HttpUtility.HtmlDecode("&#xf4ff; " + " Enter User Name"), @class = "fas font-family: 'FontAwesome' form-control _ge_de_ol" } })
                                @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group p-0 wow bounceInLeft " data-wow-delay="0.1s">
                                @Html.EditorFor(model => model.Name, new
                                {
                                    htmlAttributes = new
                                    {
                                        @placeholder = HttpUtility.HtmlDecode("&#xf4ff; " + " Enter your Name"),
                               @class = "fas font-family: 'FontAwesome' form-control _ge_de_ol"
                                    }
                                })

                                @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group p-0 wow bounceInLeft " data-wow-delay="0.1s">

                                @Html.DropDownList("RoleName", (MultiSelectList)ViewBag.Roles, "Select Bussnes Role", new
                                {
                               @class = "bx bxs-user-account  fas font-family: 'FontAwesome' form-control _ge_de_ol",
                                    style = ""
                                })
                            </div>
                            <div class="form-group p-0 wow bounceInRight " data-wow-delay="0.2s">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @placeholder = HttpUtility.HtmlDecode("&#xf084; " + " Enter Password"), @class = "fas font-family: 'FontAwesome' form-control _ge_de_ol" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group p-0 wow bounceInLeft " data-wow-delay="0.3s">
                                @Html.EditorFor(model => model.Confirm_Password, new { htmlAttributes = new { @placeholder = HttpUtility.HtmlDecode("&#xf084; " + " Confirm Password"), @class = "fas font-family: 'FontAwesome' form-control _ge_de_ol" } })
                                @Html.ValidationMessageFor(model => model.Confirm_Password, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group p-0 wow bounceInRight " data-wow-delay="0.4s">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @placeholder = HttpUtility.HtmlDecode("&#xf674; " + " Enter Your Email"), @class = "fas font-family: 'FontAwesome' form-control _ge_de_ol" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group p-0 wow bounceInLeft " data-wow-delay="0.5s">
                                @Html.EditorFor(model => model.phone_num, new { htmlAttributes = new { @placeholder = HttpUtility.HtmlDecode("&#xf879; " + " Enter phone Number"), @class = "fas font-family: 'FontAwesome' form-control _ge_de_ol" } })
                                @Html.ValidationMessageFor(model => model.phone_num, "", new { @class = "text-danger" })
                            </div> 
                            <div class="form-group p-0 wow bounceInLeft " data-wow-delay="0.5s">
                                <label>choose imge : </label>
                                @Html.TextBox("image", "", new { Type = "file", style = "height: 50px;" })
                            </div>

                            <div class="form-check py-3 wow rotateIn " data-wow-delay="0.6s">
                                <input class="form-check-input d-flex justify-content-md-start p-3" type="checkbox" value="" id="">
                                <label class="form-check-label" for="">
                                    Remember me
                                </label>
                            </div>



                            <div class="form-group p-0 wow wobble " data-wow-delay="0.6s">
                                <div class="_btn_04">
                                    <input type="submit" value="ADD Account" class="btn_log" />
                                </div>


                            </div>
                            <div class="form-group p-0  wow bounceInRight " data-wow-delay="0.6s">


                                @Html.ActionLink("Login", "Login", "Account", null, new { @class = " float-start text-info" })
                                <a href="#" class="float-right text-light">Forgot Password ?</a>

                            </div>
                            <div class="form-group nm_lk p-0  wow lightSpeedIn " data-wow-delay="0.6s"><p>Or Login With</p></div>

                            <div class="form-group pt-0">
                                <div class="_social_04">
                                    <ol>
                                        <li class="wow hinge " data-wow-delay="0.1s "><i class="fab fa-facebook-f "></i></li>
                                        <li class="wow hinge " data-wow-delay="0.2s "><i class="fab fa-twitter"></i></li>
                                        <li class="wow hinge " data-wow-delay="0.3s "><i class="fab fa-google"></i></li>
                                        <li class="wow hinge " data-wow-delay="0.4s "><i class="fab fa-instagram"></i></li>
                                        <li class="wow hinge " data-wow-delay="0.5s "><i class="fab fa-linkedin-in"></i></li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </section>


}

Car Price prediction/Views/admin/SellsCar.cshtml
@model IEnumerable<Car_Price_prediction.view_model.SellsVM>

@{
    ViewBag.Title = "SellsCar";
    ViewBag.icon = "SellsCar.png";
    <link href="~/Content/tableRespons.css" rel="stylesheet" />
}
<style>
    a {
        color: #0f101a;
        text-decoration: none;
        background-color: transparent;
    }
</style>
<br />
<br />

<div class="container">
    <h1>Sells Car</h1>
    <table class="rwd-table">
        <tbody>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Brand)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Model)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Year)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Transmission)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Color)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Frontimage)
                </th>
                <th>Oner Name</th>
                <th>Email</th>
                <th>

                </th>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td data-th=" Make">
                        @Html.DisplayFor(modelItem => item.Brand)
                    </td>
                    <td data-th=" Model">
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td data-th=" Year">
                        @Html.DisplayNameFor(model => model.Year)
                    </td>
                    <td data-th="T_Type">
                        @Html.DisplayFor(modelItem => item.Transmission)
                    </td>
                    <td data-th=" Color">
                        @Html.DisplayFor(modelItem => item.Color)
                    </td>
                    <td data-th=" Price">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td data-th=" image">
                        <img src="~/img/Car_Image/@Html.DisplayFor(modelItem=>item.Frontimage)" alt="@Html.DisplayFor(modelItem => item.Frontimage)" style="width:90px ;" />

                    </td>
                    <td data-th=" UserName">
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td data-th=" Email">
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td data-th=" Delete">
                       <a class="btn btn-outline-info px-3" href="/admin/Deletecar/@item.ID">Delete</a>

                    </td>
                </tr>

            }

        </tbody>
    </table>

</div>

Car Price prediction/Views/admin/USER_Accounts.cshtml
@model IEnumerable<Car_Price_prediction.view_model.Registration_Vm>

@{ ViewBag.Title = "USER_Accounts";
    ViewBag.icon = "USER_Accounts.png";
    <link href="~/Content/tableRespons.css" rel="stylesheet" /> }


<style>
    a {
        color: #0f101a;
        text-decoration: none;
        background-color: transparent;
    }
</style>


<div class="container p-5">
    <h1>USER Accounts</h1>
    <table class="rwd-table">
        <tbody>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.User_Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Age)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.phone_num)
                </th>
                <th>

                </th>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td data-th=" User_Name">
                        @Html.DisplayFor(modelItem => item.User_Name)
                    </td>
                    <td data-th=" Name">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td data-th=" Age">
                        @Html.DisplayFor(modelItem => item.Age)
                    </td>
                    <td data-th=" Email" style="color:black">
                        @Html.DisplayFor(modelItem => item.Email, new { @class = "h3.link-colour" })
                    </td>
                    <td data-th=" phone_num">
                        @Html.DisplayFor(modelItem => item.phone_num)
                    </td>
                    <td data-th=" Delete">
                        <form method="post" action="~/admin/delete">
                            <input type="hidden" id="UserId" name="UserId" value="@item.ID" />
                            <input type="submit" value="Delete" class="btn btn-outline-info px-3"/>
                        </form>
                        
                    </td>
                </tr>          
                }

        </tbody>
    </table>

</div>

Car Price prediction/Views/admin/User_massage.cshtml
@model IEnumerable<Car_Price_prediction.Models.CustomerMessage>

@{ ViewBag.Title = "Useer_massage";
    ViewBag.icon = "Useer_massage.png";
    <link href="~/Content/tableRespons.css" rel="stylesheet" /> }

<section class="home-section">

    <div class="container">
        <h1>User Massage</h1>
        <table class="rwd-table">
            <tbody>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Subject)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Message)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.phoneNumber)
                    </th>
                    <th>

                    </th>

                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td data-th=" Name">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td data-th=" Email">
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td data-th=" Subject">
                            @Html.DisplayFor(modelItem => item.Subject)
                        </td>
                        <td data-th=" Massage">
                            @Html.DisplayFor(modelItem => item.Message)
                        </td>
                        <td data-th=" Namber">
                            @Html.DisplayFor(modelItem => item.phoneNumber)
                        </td>
                       <td>

                       </td>
                    </tr>
    }

            </tbody>
        </table>

    </div>
</section>