Car Price prediction/Controllers/SellsController.cs
using Car_Price_prediction.Models;
using Car_Price_prediction.Services;
using Car_Price_prediction.view_model;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Sell_your_car.view_model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Car_Price_prediction.Controllers
{
   
    public class SellsController : Controller
    {
        ApplicationDbcontext _context = new ApplicationDbcontext();
        [Authorize]
        public ActionResult SellYourCar ()
        {
            var userID = User.Identity.GetUserId();

            AccountConstraints accountConstraints = new AccountConstraints();
   /*         var car_count = accountConstraints.CarSellsCount(userID); 

            if (User.IsInRole("Dealer") && car_count >= 15 || !User.IsInRole("Dealer") && car_count >= 2)
            {
                throw new Exception("You have reached the limit of 20 car inserts for this month.");
                //return View("LimitedInsert");
            }*/

            var car_Brand = _context.Brands_Models.Select(c => c.Brand).Distinct().ToList();
            ViewBag.Brand = new MultiSelectList(car_Brand);
        
            var governorates = _context.Governorate.Select(c => new {
                GatID = c.id,
                GatName = c.governorate_name_en
            }).ToList();
            ViewBag.governorates = new MultiSelectList(governorates, "GatID", "GatName");
          

            List<FeatureSelection> featureSelection = _context.features.Select(x => new FeatureSelection
            {
                FeaturesID = x.ID,
                Features = x.Feature,
                ISselected = false,

            }).ToList();
            var ShowroomData = _context.showroomsForTrader.FirstOrDefault(x => x.UserID == userID);
            if (User.IsInRole("Dealer"))
            {
                var model = new SellYourCarViewModel
                {
                    TraderName = ShowroomData.TraderName,
                    ShowroomName = ShowroomData.ShowroomName,
                    ShowroomDiscription = ShowroomData.Discription,
                    Logo = ShowroomData.Logo,
                    CoverImage = ShowroomData.CoverImage,
                    ShowroomPhoneNumber0 = ShowroomData.PhoneNumber0,
                    ShowroomPhoneNumber1 = ShowroomData.PhoneNumber1,
                    ShowroomEmail = ShowroomData.Email,

                    CarFeatures = featureSelection,
                    colors = new Colors().getcolors(),

                };
                return View(model);
            }
            else
            {
                var model = new SellYourCarViewModel
                {
                    CarFeatures = featureSelection,
                    colors = new Colors().getcolors(),
                    Name = _context.Users.Where(c => c.Id == userID).Select(c => c.Name).FirstOrDefault(),
                    Email = _context.Users.Where(c => c.Id == userID).Select(c => c.Email).FirstOrDefault(),
                    PhoneNumber = _context.Users.Where(c => c.Id == userID).Select(c => c.PhoneNumber).FirstOrDefault(),
                };
                return View(model);
            }
           
        }
        [HttpPost]
        [Authorize]
        public ActionResult SellYourCar(SellYourCarViewModel cars, HttpPostedFileBase image1,
            HttpPostedFileBase image2, HttpPostedFileBase image3,HttpPostedFileBase image4) {
            var car_Brand = _context.Brands_Models.Select(c => c.Brand).Distinct().ToList();
            ViewBag.Brand = new MultiSelectList(car_Brand);

      

            var governorates = _context.Governorate.Select(c => new {
                GatID = c.id,
                GatName = c.governorate_name_en
            }).ToList();
            ViewBag.governorates = new MultiSelectList(governorates, "GatID", "GatName");
            // ___________________________________________
            Cars car = new Cars();

            var userID = User.Identity.GetUserId();
            car.Brand = cars.Brand;
            car.Model = cars.Model;
            car.Body = cars.Body;
            car.Fuel = cars.Fuel;
            car.Color = cars.Color;
            car.Transmission = cars.Transmission;
            car.Year = cars.Year;
            car.Engine_CC = cars.Engine_CC;
            car.Kilometers_Driven = cars.Kilometers_Driven;
            car.Color = cars.Color;
            car.City = cars.City;
            car.Price = cars.Price;
            car.Fabrica = cars.Fabrica;
            car.Discription = cars.Discription;
            car.UserID = userID;
           
            //add the feature for car 


            CarImages carImages = new CarImages();
            /*   int lastcarId = _context.Cars.Max(item => item.ID);
               carImages.CarID = lastcarId;*/

            var selectedoptions_featureID = cars.CarFeatures.Where(x => x.ISselected == true).Select(x => x.FeaturesID).ToList();

            var addedList = selectedoptions_featureID.Select(x => new CarFeatures
            {
                FeatureID = x,
            }).ToList();
           

            if (image1 != null && image1.ContentLength > 0)
            {

                string ImageFileName1 = Path.GetFileName(image1.FileName);
                string FolderPath1 = Path.Combine(Server.MapPath("~/img/Car_Image"), ImageFileName1);
                image1.SaveAs(FolderPath1);


                carImages.Frontimage = ImageFileName1;
            }
            if (image2 != null && image2.ContentLength > 0)
            {

                string ImageFileName2 = Path.GetFileName(image2.FileName);
                string FolderPath2 = Path.Combine(Server.MapPath("~/img/Car_Image"), ImageFileName2);
                image2.SaveAs(FolderPath2);


                carImages.Backimage = ImageFileName2;

            }
            if (image3 != null && image3.ContentLength > 0)
            {
                string ImageFileName3 = Path.GetFileName(image3.FileName);
                string FolderPath3 = Path.Combine(Server.MapPath("~/img/Car_Image"), ImageFileName3);
                image3.SaveAs(FolderPath3);

                carImages.RightSideimage = ImageFileName3;
            }
            if (image4 != null && image4.ContentLength > 0)
            {
                string ImageFileName4 = Path.GetFileName(image4.FileName);
                string FolderPath4 = Path.Combine(Server.MapPath("~/img/Car_Image"), ImageFileName4);
                image4.SaveAs(FolderPath4);

                carImages.LeftSideimage = ImageFileName4;
            }
            _context.Cars.Add(car);
            _context.carFeatures.AddRange(addedList);
            _context.carImages.Add(carImages);
            _context.SaveChanges();


            return RedirectToAction("SellYourCar");
        }


        public ActionResult Car_For_Sell(int page = 1)
        {
            var car_model_year = _context.Cars.Select(c => c.Year).Distinct().ToList();
            ViewBag.year = new MultiSelectList(car_model_year);

            var car_model_price = _context.Cars.Select(c => c.Price).Distinct().ToList();
            ViewBag.Price = new MultiSelectList(car_model_price);

            var Engine_CC = _context.Cars.Select(c => c.Engine_CC).Distinct().ToList();
            ViewBag.car_Engine_CC = new MultiSelectList(Engine_CC);

            // prepare vm to be passsed to the view 
            // get car list from db
  
            List <car_detials_vm> Cars = _context.Cars.Select(x => new car_detials_vm
            {
                
                ID = x.ID,
                UserID = x.UserID,
                Brand = x.Brand,
                Model =x.Model,
                Body = x.Body,
                Fuel = x.Fuel,
                Engine_CC_Range = x.Engine_CC,
                Color = x.Color,
                City = x.City,
                Governorate = _context.Governorate.FirstOrDefault(c => c.id == 
                _context.Cities.FirstOrDefault(v => v.city_name_en.Equals(x.City)).governorateID).governorate_name_en,
                Transmission = x.Transmission,
                Kilometers_Driven = x.Kilometers_Driven,
                Fabrica = x.Fabrica,
                yearRange = x.Year,
                PriceRange = x.Price,
                Active = x.Active,
                Frontimage = _context.carImages.FirstOrDefault(v => v.CarID == x.ID) != null ?
                _context.carImages.FirstOrDefault(v => v.CarID == x.ID).Frontimage.ToString() : null, 
                 Backimage = _context.carImages.FirstOrDefault(v => v.CarID == x.ID) != null ?
                _context.carImages.FirstOrDefault(v => v.CarID == x.ID).Backimage.ToString() : null,
                RightSideimage = _context.carImages.FirstOrDefault(v => v.CarID == x.ID) != null ?
                _context.carImages.FirstOrDefault(v => v.CarID == x.ID).RightSideimage.ToString() : null,
                LeftSideimage = _context.carImages.FirstOrDefault(v => v.CarID == x.ID) != null ?
                _context.carImages.FirstOrDefault(v => v.CarID == x.ID).LeftSideimage.ToString() : null,
                UserName = x.User.UserName,
                Phone_Namber = x.User.PhoneNumber
            }).Where(x => x.UserID != null).Where(x => x.Active == true).ToList();

            // get make selection list
            List<MakerSelection> BrandList = _context.Cars.Select(x => new MakerSelection
            {
                Brand = x.Brand,
                ISselected = false
            }).Distinct().ToList();
            // get Size selection list
   
          
            var model = new CarListVM
            {
                Cars = Cars,
                Selections_FOR_MAKE = BrandList,
              
                Sizepage = 4,
                car_Data = Cars.OrderBy(d => d.ID),
                CurrentPage = page,
                Price0 = 0,

Car Price prediction/Views/Sells/Car_For_Sell.cshtml
@model Car_Price_prediction.view_model.CarListVM

@{
    ViewBag.Title = "Car_For_Sell";
    ViewBag.icon = "Car_For_Sell.png";

}
<style>

</style>
@using (Html.BeginForm("Car_For_Sell", "Sells", FormMethod.Post, new { @class = "form", id = "Filterform" }))
{

    <div class="row m-0">
        <div class="col-md-3 m-3">
            @Html.Partial("_filter")

        </div>




        <!-- Main content -->
        @if (Model.ID == 0)
        {
            <div class="col-md-8">

                <div class="row" id="tdata">

                    @foreach (var item in Model.Paginatedcar_data())
                    {

                        <div class="container h-150">
                            <div class="row d-flex justify-content-center align-items-center ">
                                <div class="col ">
                                    <div class="card mb-4 rounded">
                                        <div>
                                            <div class="card-body p-4">
                                                <div class="row align-items-center">
                                                    <div class="col-md-4 d-flex justify-content-center align-items-center ">
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                <a target="_blank" href="~/img/Car_Image/@item.Frontimage">
                                                                    <img class="img-fluid mb-1 " src="~/img/Car_Image/@item.Frontimage" alt="@item.Frontimage" style="width:300px; height:auto;">
                                                                </a>
                                                            </div>

                                                            <div class="col text-center">
                                                                <a target="_blank" href="~/img/Car_Image/@item.Backimage">
                                                                    <img class="img-fluid mb-1 " src="~/img/Car_Image/@item.Backimage" alt="@item.Backimage" style="width:70px; height:auto;">
                                                                </a>
                                                            </div>
                                                            <div class="col text-center">
                                                                <a target="_blank" href="~/img/Car_Image/@item.RightSideimage">
                                                                    <img class="img-fluid mb-1 " src="~/img/Car_Image/@item.RightSideimage" alt="@item.RightSideimage" style="width:70px; height:auto;">
                                                                </a>
                                                            </div>
                                                            <div class="col text-center">
                                                                <a target="_blank" href="~/img/Car_Image/@item.LeftSideimage">
                                                                    <img class="img-fluid mb-1 " src="~/img/Car_Image/@item.LeftSideimage" alt="@item.LeftSideimage" style="width:70px; height:auto;">
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-4 text-center">

                                                        <div class="row ">
                                                            <div class="col-md-12 text-center">
                                                                <h4 class="text-uppercase mb-4 d-flex justify-content-center">@Html.DisplayFor(modelItem => item.Brand) @Html.DisplayFor(modelItem => item.Model)  @Html.DisplayFor(modelItem => item.yearRange)  </h4>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                <h6 class="text-uppercase mb-4 d-flex justify-content-center">@Html.DisplayFor(modelItem => item.UserName) <span class="text-warning">||</span> <span class="text-danger">@Html.DisplayFor(modelItem => item.Phone_Namber)  </span>  </h6>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-12 text-center">
                                                                <h6 class="text-uppercase mb-4 d-flex justify-content-center">@Html.DisplayFor(modelItem => item.Governorate) <span class="text-warning">||</span> <span class="text-danger">@Html.DisplayFor(modelItem => item.City)  </span>  </h6>
                                                            </div>
                                                        </div>
                                                        @*<div class="row ">
                                                                <div class="col-md-6  border border-secondary bg-secondary rounded-pill text-center m-1">
                                                                    <b class=" text-light  " data-toggle="tooltip" title="Car Transmission Tybe is :   @Html.DisplayFor(modelItem => item.Transmission)">@Html.DisplayFor(modelItem => item.Transmission) </b>
                                                                </div>
                                                                <div class="col-md-6   border border-secondary bg-secondary rounded-pill  text-center m-1">
                                                                    <b class=" text-light  " data-toggle="tooltip" title="Car Body Style is :   @Html.DisplayFor(modelItem => item.Body)">@Html.DisplayFor(modelItem => item.Body) </b>
                                                                </div>

                                                            </div>*@

                                                    </div>

                                                    <div class="col-md-2 text-center ">


                                                        <h4>
                                                            <i class="far fa-calendar-alt " data-toggle="tooltip" title="@Html.DisplayFor(modelItem => item.yearRange)" style="font-size:25px"></i>

                                                            <i class="fa fa-cogs  " data-toggle="tooltip" title="@Html.DisplayFor(modelItem => item.Transmission)" style="font-size:25px"></i>

                                                            <i class="	far fa-address-card " data-toggle="tooltip" title="@Html.DisplayFor(modelItem => item.UserName)" style="font-size:25px"></i>


                                                        </h4>

                                                        <h6 class="mr-3 text-primary text-center " data-toggle="tooltip" title="Car Price is : @Html.DisplayFor(modelItem => item.PriceRange) EGP"> @Html.DisplayFor(modelItem => item.PriceRange) EGP </h6>
                                                    </div>
                                                    <div class="col-md-2 d-flex justify-content-center">
                                                        <a class="btn btn-outline-secondary px-3 rounded animate-down-2" href="/Sells/Detalis/@item.ID">Detalis</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }


                </div>

                <ul class="pagination" style="justify-content:center">
                    @*<a class="page-link" href="@Url.Action("Car_For_Sell", new { page = Model.Previous()})"> << Previous </a>*@
                    <li>
                        <button type="submit" name="" style="border-radius: 25px;" value="" formaction=@Url.Action("Car_For_Sell", new { page = Model.Previous() }) formmethod="post" class="fas fa-fast-backward page-link" />
                    </li>

                    @if (Model.pagestart() > 2)
                    {
                        <li class="@(1 == Model.CurrentPage ? "page-item active" : "page-item")">
                            <input type="submit" name="" value="1" style="border-radius: 25px;" formaction=@Url.Action("Car_For_Sell", new { page =1
                        }) formmethod="post" class="page-link" />
                        </li>
                        <li>
                            <div class="btn btn-dark rounded-circle page-link">
                                <i class="fa fa-ellipsis-h fa_custom "></i>
                            </div>
                        </li>
                    }
                    @{ int ii;}
                    @for (ii = Model.pagestart(); ii <= Model.PageCount(); ii++)
                    {
                        if (ii < 9)
                        {

                            <li class="@(ii == Model.CurrentPage ? "page-item active" : "page-item")">
                                <input type="submit" name="" style="border-radius: 25px;" value="@ii" formaction=@Url.Action("Car_For_Sell", new
                                { page = ii}) formmethod="post" class="page-link" />
                            </li>
                        }
                        else
                        {
                            if (ii == Model.CurrentPage && ii > 8)
                            {
                                for (int u = Model.pagestart1(); u <= Model.CurrentPage; u++)
                                {
                                    <li class="@(u == Model.CurrentPage  ? "page-item active" : "page-item")">
                                        <input type="submit" name="" style="border-radius: 25px;" value="@u" formaction=@Url.Action("Car_For_Sell", new
                                      {page = u}) formmethod="post" class="page-link" />
                                    </li>

                                }

                            }
                        }
                    }
                    @*// [page] دي بتخلي ال ...  تظهر اول لما الصفحه تذيد عن 8*@
                    @if (ii > Model.PageCount() && ii > 9 && Model.PageCount() != Model.CurrentPage)
                    {
                        ii--;
                        <li>
                            <div class="btn btn-dark rounded-circle page-link">
                                <i class="fa fa-ellipsis-h fa_custom "></i>
                            </div>
                        </li>
                        <li class="@(ii == Model.CurrentPage ? "page-item active" : "page-item")">
                            <input type="submit" style="border-radius: 25px;" name="" value="@ii" formaction=@Url.Action("Car_For_Sell", new { page =ii
                        }) formmethod="post" class="page-link" />
                        </li>
                    }

                    @*<a class="page-link" href="@Url.Action("Car_For_Sell", new { page =Model.Next()})"> >> Next </a>*@
                    <li>
                        <button type="submit" style="border-radius: 25px;" name="" value="" formaction=@Url.Action("Car_For_Sell", new { page =Model.Next()}) formmethod="post" class="fas fa-fast-forward page-link" />
                    </li>
                </ul>
            </div>
        }

    </div>

}
@*  @{Html.RenderAction("Slider", "Home");}*@




<!--<script>
    function getcarslist(brand) {

        var brandlist = brand.innerText.trim() ;
        console.log(brandlist);
        $.ajax({
            type: "Post",
            async: false,
            url: "/Sells/GetCarsListbyAjax",
            data: { brand: brandlist },
            success: function (data) {
                console.log(data)
                let Items = '';-->
@*    $.each(data, function (index) {

        Items += '<option value="' + data[index].Text + '">' + data[index].Text + "</option>";
    });*@
@* console.log(Items);*@
<!--$('.carModels').html(Items);
            },
            error: function () { alert("error"); },
        })
    }
</script>-->
@section scripts{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    @*    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>*@
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script src="~/Scripts/filter_Prange.js"></script>

}


<script>
        var price0_js =@Model.Price0;
        var price1_js =@Model.Price1;




</script>