Car Price prediction/Controllers/Car_finderController.cs
using Car_Price_prediction.Models;
using Car_Price_prediction.view_model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace Car_Price_prediction.Controllers
{
    public class Car_finderController : Controller
    {
        ApplicationDbcontext _context = new ApplicationDbcontext();
        
        public ActionResult Cars_filter(int page=1)
        {
            var car_model_year = _context.Cars.Select(c => c.Year).Distinct().ToList();
            ViewBag.year = new MultiSelectList(car_model_year);

           /* var car_model_price = _context.Cars.Select(c => c.Price).Distinct().ToList();
            ViewBag.Price = new MultiSelectList(car_model_price);*/

            var car_Engine_CC = _context.Cars.Select(c => c.Engine_CC).Distinct().ToList();
            ViewBag.car_Engine_CC = new MultiSelectList(car_Engine_CC);
            // prepare vm to be passsed to the view 
            // get car list from db
            List<car_detials_vm> cars = _context.Cars.Select(x => new car_detials_vm
            {
                ID = x.ID,
                UserID =x.UserID,
                Brand = x.Brand,
                Body = x.Body,
                Fuel = x.Fuel,
                Engine_CC_Range = x.Engine_CC,
                Color = x.Color,
                City = x.City,
                Transmission = x.Transmission,
                Kilometers_Driven = x.Kilometers_Driven,
                yearRange = x.Year,
                PriceRange = x.Price,
                image = _context.carImages.FirstOrDefault(v => v.CarID == x.ID) != null ?
                _context.carImages.FirstOrDefault(v => v.CarID == x.ID).Frontimage.ToString() : null,

            }).ToList();

            // get Brand selection list
            List<MakerSelection> BrandList = _context.Cars.Select(x => new MakerSelection
            {
                Brand = x.Brand,
                ISselected = false
            }).Distinct().ToList();
            // get Size selection list
    
            var model = new CarListVM
            {
                Dealars = _context.showroomsForTrader.Select(x => new DealerVM
                {
                    UserID = x.UserID,
                }).ToList(),
                Cars = cars,
     
                Selections_FOR_MAKE = BrandList,
               
                Sizepage = 12,
                car_Data = cars.OrderBy(d => d.ID),
                CurrentPage = page,
                Price0 = 0,
                Price1 = 3500000.0,
            };

            return View(model);
        }
        [HttpPost]
        public ActionResult Cars_filter(CarListVM model, int page = 1)
        {
            var car_model_year = _context.Cars.Select(c => c.Year).Distinct().ToList();
            ViewBag.year = new MultiSelectList(car_model_year);

            var car_model_price = _context.Cars.Select(c => c.Price).Distinct().ToList();
            ViewBag.Price = new MultiSelectList(car_model_price);

            var car_Engine_CC = _context.Cars.Select(c => c.Engine_CC).Distinct().ToList();
            ViewBag.car_Engine_CC = new MultiSelectList(car_Engine_CC);

            // get the selected Brand options say bmw and oudi
            var selectedoptions_for_Brand = model.Selections_FOR_MAKE.Where(x => x.ISselected == true).Select(x => x.Brand).ToList();
            // get the selected size  options say larg and compact
         
            // get car list from db
            model.Cars = _context.Cars.Select(x => new car_detials_vm
            {
                ID = x.ID,
                Brand = x.Brand,
                Body = x.Body,
                Fuel = x.Fuel,
                Engine_CC_Range = x.Engine_CC,
                Color = x.Color,
                City = x.City,
                Transmission = x.Transmission,
                Kilometers_Driven = x.Kilometers_Driven,
              /*  Fabrica = x.Fabrica,*/
                yearRange = x.Year,
                PriceRange = x.Price,
                image = _context.carImages.FirstOrDefault(v => v.CarID == x.ID) != null ?
                _context.carImages.FirstOrDefault(v => v.CarID == x.ID).Frontimage.ToString() : null,
            }).Where(c => selectedoptions_for_Brand.Contains(c.Brand) || selectedoptions_for_Brand.Count == 0)
                   .Where(x => x.yearRange >= model.year0 && x.yearRange <= model.year1 || x.yearRange >= model.year0 && model.year1 == null
                   || x.yearRange <= model.year1 && model.year0 == null || model.year0 == null && model.year1 == null)
                   .Where(x => x.PriceRange >= model.Price0 && x.PriceRange <= model.Price1 || model.Price0 == null || model.Price1 == null)
                   .Where(e => e.Fuel == model.Fuel || model.Fuel == null || model.Fuel == "")
                   .Where(e => e.Transmission == model.Transmission || model.Transmission == null || model.Transmission == "")
                   .Where(e => e.Engine_CC_Range >= model.Engine_CC0 && e.Engine_CC_Range <= model.Engine_CC1 || e.Engine_CC_Range >= model.Engine_CC0 && model.Engine_CC1 == null ||
                    e.Engine_CC_Range <= model.Engine_CC1 && model.Engine_CC0 == null || model.Engine_CC0 == null && model.Engine_CC1 == null)
                   .Where(n => n.City == model.City || model.City== null)
                   .Where(n => n.Body == model.Body || model.Body== null).ToList();

            // get Brand selection list
            List<MakerSelection> BrandList = _context.Cars.Select(x => new MakerSelection
            {
                Brand = x.Brand,
                ISselected = false
            }).Distinct().ToList();
  

            var Carss = new CarListVM
            {
                Dealars = _context.showroomsForTrader.Select(x => new DealerVM
                {
                    UserID = x.UserID,
                }).ToList(),
                Cars = model.Cars,
                Selections_FOR_MAKE = BrandList,
               
                Sizepage = 12,
                car_Data = model.Cars.OrderBy(d => d.ID),
                CurrentPage = page,
                Price0 = model.Price0,
                Price1 = model.Price1,
            };
            return View(Carss);
        }

        public ActionResult Carpricepredict()
        {
            return View();
        }
        public ActionResult Detalis(int? id)
        {
            var foundID = _context.Cars.Find(id);
            if (foundID == null)
            {

                return RedirectToAction("notFound", "home");
            }
            try
            {
                ViewBag.img = _context.carImages.FirstOrDefault(v => v.CarID == id) != null ?
                 _context.carImages.FirstOrDefault(v => v.CarID == id).Frontimage.ToString() : null;
             
                
                Cars car =
                _context.Cars.FirstOrDefault(v => v.ID == id) != null ?
                   _context.Cars.FirstOrDefault(v => v.ID == id) : null;
                return View(car);
            }
            catch (Exception)
            {
                return RedirectToAction("error");
                throw;
            }
            
        
        }
    }
}

Car Price prediction/Views/Car_finder/Carpricepredict.cshtml
@{
    ViewBag.Title = "Carpricepredict";
    ViewBag.icon = "Carpricepredict.png";
}
<style>
    body {
        background-image: url('../../img/blueCar.jpg');
    }

    .responsive-iframe {
        width: 100%;
        height: 920px;
    }

    /* Extra small devices (phones, 600px and down) */
    @@media only screen and (max-width: 600px) {
        .responsive-iframe {
            height: 1400px;
        }
    }

    /* Small devices (portrait tablets and large phones, 600px and up) */
    @@media only screen and (min-width: 600px) {
        .responsive-iframe {
            height: 1000px;
        }
    }
</style>



<center>
    <!-- https://carpricepredictionv3.onrender.com/ -->
    <iframe id="iframe" class="responsive-iframe" src="https://egyptcarpricepredictionv1.onrender.com/" scrolling="no"
            style=" top:0; left:0; bottom:0; right:0;  border:none; margin:0; padding:0; overflow:hidden;"></iframe>


</center>

Car Price prediction/Views/Car_finder/Cars_filter.cshtml
@model Car_Price_prediction.view_model.CarListVM
@{
    ViewBag.Title = "Cars_filter";
    ViewBag.icon = "Cars_filter.png";
}
<link href="~/Content/popupFilter.css" rel="stylesheet" />
<!-- Carousel Start -->
<div class="container-fluid p-0" style="margin-bottom: 30px;">
    <div id="header-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active" id="w-100">
                <img class="w-100" src="~/img/hed1.jpg" alt="Image">

                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 900px;">
                        <h4 class="text-white text-uppercase mb-md-3">Car Finder</h4>
                        <h4 class="display-4 text-white mb-md-3">Find your car easily &#129300;</h4>
                        <a href="#find" class="btn btn-primary py-md-3 px-md-5 mt-2">Find Now</a>
                    </div>
                </div>
            </div>
            <div class="carousel-item" id="w-100">
                <img class="w-100" src="~/img/hed2.jpg" alt="Image">

                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 900px;">
                        <h4 class="text-white text-uppercase mb-md-3">Car Finder</h4>
                        <h4 class="display-4 text-white mb-md-3">Choose your car specifications and you will find them &#129488;</h4>
                        <a href="#find" class="btn btn-primary py-md-3 px-md-5 mt-2">Find Now</a>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-prev-icon mb-n2"></span>
            </div>
        </a>
        <a class="carousel-control-next" href="#header-carousel" data-slide="next">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-next-icon mb-n2"></span>
            </div>
        </a>
    </div>
</div>
<!-- Carousel End -->
@*<div class="triggers">

        <label class=" w-100 text-center" for="popup-2"><i class="fa fa-filter text-center"></i></label>
    </div>*@


@using (Html.BeginForm("Cars_filter", "Car_finder", FormMethod.Post, new { @class = "form", id = "Filterform" }))
{






    <main class="row m-0">
        <aside class="col-md-3 m-3">

            <input type="checkbox" class="vcms__popup-check" name="popup-2" id="popup-2">
            <div class="vcms__popup">
                <div class="inner">
                    <div class="header">
                        <i class="fa fa-filter"></i>
                        Filter..
                        <label class="close" for="popup-2">X</label>
                    </div>
                    <div class="txt">
                        @Html.Partial("_filter")
                    </div>
                    <div class="footer">

                        <label class="close" for="popup-2">Close Filter!</label>
                    </div>
                </div>
            </div>



            @{
                var first = true;
            }

            <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
                <div class="banner">

                    <div class="carousel-inner justify-content-center">
                        @foreach (var item in Model.Cars.Where(c => c.UserID != null))
                        {
                            foreach (var item1 in Model.Dealars)
                            {

                                if (item1.UserID.Contains(item.UserID))
                                {

                                    <div class="carousel-item @(first?Html.Raw("active"):Html.Raw(""))" data-bs-interval="5000">
                                        <img class="img-fluid mb-4" src="~/img/Car_Image/@item.image" style="width:300px ; height :300px; background-color:none ;" />
                                        <div class="" style="text-align:center">
                                            <h1>@item.Brand</h1>
                                            <p>@item.PriceRange</p>
                                        </div>

                                    </div>
                                    first = false;

                                }
                            }
                        }



                    </div>

                </div>

            </div>



        </aside>




















        <!-- Main content -->
        <div class="col-md-8">



            <div class="row" id="tdata">

                @if (Model.Cars.Count() == 0)
                {<!-- Error Page -->

                    <div class="d-flex align-items-center justify-content-center vh-100">
                        <div class="text-center row">
                            <div class=" col-md-6">

                                <img src="~/img/Error.gif" class="img-fluid" style="width:300px" />
                            </div>
                            <div class=" col-md-6 mt-5">
                                <p class="fs-3">  <span class="text-danger">Opps!</span> Your car  not available now.!!&#128517;</p>
                                <p class="lead">
                                    You can choose specifications closer than these &#128522
                                </p>
                                <a href="~/Home/Index/" class="btn btn-outline-primary">Go Home</a>

                            </div>

                        </div>
                    </div>
                }


                @foreach (var item in Model.Paginatedcar_data())
                {
                    <div class="col-lg-4 col-md-6 col-md-12 wow bounceInUp mb-4" data-wow-delay="0.3s">
                        <div class="rent-item ">
                            <img class="img-fluid mb-4" src="~/img/Car_Image/@item.image" alt="@item.image">

                            <h4 class="text-uppercase ">@Html.DisplayFor(modelItem => item.Brand)</h4>
                            <h5 class="text-uppercase text-primary ">  @Html.DisplayFor(modelItem => item.PriceRange) EGP</h5>
                            <div class="d-flex justify-content-center mb-4">
                                <div class="px-2">
                                    <i class="fa fa-car text-primary mr-1"></i>
                                    <span>@Html.DisplayFor(modelItem => item.yearRange)</span>
                                </div>
                                <div class="px-2 border-left border-right">
                                    <i class="fa fa-cogs text-primary mr-1"></i>
                                    <span> @Html.DisplayFor(modelItem => item.Transmission)</span>
                                </div>
                                <div class="px-2">
                                    <i class="fa fa-road text-primary mr-1"></i>
                                    <span>  @Html.DisplayFor(modelItem => item.yearRange)</span>
                                </div>
                            </div>

                            <a class="btn btn-outline-info px-3" href="/Car_finder/Detalis/@item.ID">Detalis</a>

                        </div>

                    </div>

                }

            </div>
            <ul class="pagination" style="justify-content:center">
                @*<a class="page-link" href="@Url.Action("Cars_filter", new { page = Model.Previous()})"> << Previous </a>*@
                <li style="margin-right: 10px;">

                    <button type="submit" name="" style=" border-radius: 25px; width:50px; height:50px" value="" formaction=@Url.Action("Cars_filter", new { page = Model.Previous() }) formmethod="post" class="fas fa-fast-backward page-link" />
                </li>

                @if (Model.pagestart() > 2)
                {
                    <li class="@(1 == Model.CurrentPage ? "page-item active" : "page-item")">
                        <input type="submit" style=" border-radius: 25px; width: 50px; height: 50px" name="" value="1" formaction=@Url.Action("Cars_filter", new { page =1
                        }) formmethod="post" class="page-link" />
                    </li>
                    <li>
                        <div class="btn btn-dark rounded-circle page-link font-weight-bold" style=" border-radius: 25px; width: 50px; height: 50px;">
                            ...
                        </div>
                    </li>
                }
                @{ int ii;}
                @for (ii = Model.pagestart(); ii <= Model.PageCount(); ii++)
                {
                    if (ii < 4)
                    {

                        <li class="@(ii == Model.CurrentPage ? "page-item active" : "page-item")">
                            <input type="submit" style=" border-radius: 25px; width: 50px; height: 50px" name="" value="@ii" formaction=@Url.Action("Cars_filter", new
                                { page = ii}) formmethod="post" class="page-link" />
                        </li>
                    }
                    else
                    {
                        if (ii == Model.CurrentPage && ii > 3)
                        {
                            for (int u = Model.pagestart1(); u <= Model.CurrentPage; u++)
                            {
                                <li class="@(u == Model.CurrentPage  ? "page-item active" : "page-item")">
                                    <input type="submit" style=" border-radius: 25px; width: 50px; height: 50px" name="" value="@u" formaction=@Url.Action("Cars_filter", new
                                      {page = u}) formmethod="post" class="page-link" />
                                </li>

                            }

                        }
                    }
                }

                @if (ii > Model.PageCount() && ii > 4 && Model.PageCount() != Model.CurrentPage)
                {
                    ii--;
                    <li>
                        <div class="btn btn-dark rounded-circle page-link font-weight-bold" style=" border-radius: 25px; width: 50px; height: 50px;">
                            . . .
                        </div>
                    </li>
                    <li class="@(ii == Model.CurrentPage ? "page-item active" : "page-item")">
                        <input type="submit" style=" border-radius: 25px; width: 50px; height: 50px" name="" value="@ii" formaction=@Url.Action("Cars_filter", new { page =ii
                        }) formmethod="post" class="page-link" />
                    </li>
                }

                @*<a class="page-link" href="@Url.Action("Cars_filter", new { page =Model.Next()})"> >> Next </a>*@
                <li style="margin-left: 10px;">
                    <button type="submit" name="" style=" border-radius: 25px; width: 50px; height: 50px" value="" formaction=@Url.Action("Cars_filter", new { page =Model.Next()} ) formmethod="post" class="fas fa-fast-forward page-link" />
                </li>
            </ul>

        </div>
    </main>





}


@section scripts{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <script src="~/Scripts/filter_Prange.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
}
<script>
        var price0_js =@Model.Price0;
        var price1_js =@Model.Price1;
</script>